### ISSUE TITLE
excellent work ! How should I validate the training results? 

### ISSUE THREAD

**Issue by StellarOdys2ey** [tangli-udel/DEAL#1]
hope the test code can be updated. Thanks.

**Comment by tangli-udel** [comment]
Will update soon, thank you!

**Comment by tangli-udel** [comment]
The evaluation code is updated [here](https://github.com/tangli-udel/DEAL?tab=readme-ov-file#evaluations).

**Comment by StellarOdys2ey** [comment]
> The evaluation code is updated [here](https://github.com/tangli-udel/DEAL?tab=readme-ov-file#evaluations).

thanks!
