### ISSUE TITLE
Something strange about the Disentanglability result on EuroSAT

### ISSUE THREAD

**Issue by StellarOdys2ey** [tangli-udel/DEAL#3]
Sorry to bother you. I trained ViT-B/32 on the EuroSAT dataset using your code and evaluated concept-level explanation disentanglability through exp_disentanglability.ipynb. After just one epoch of training, I found that the value reached 0.3704, which is significantly higher than the result (0.192) reported in your paper. Could there be an issue with the evaluation code?        Additionally, I couldn't reproduce the disentanglability and localizability results for zero-shot ViT-B/32 either. I would greatly appreciate any guidance you could provide.

**Comment by tangli-udel** [comment]
Hi,

Thank you for bringing this up, there is indeed a bug in our code and some details are missing from the paper.

1. We missed a temperature parameter in the sigmoid_metric() function. Now it has been updated and the metric scale should be correct. Thank you again for the debugging.

2. We use adaptive batch sizes for different datasets to alleviate the ambiguity within a batch. Specifically, we use a batch size that is smaller than the number of classes in the dataset. For example, we use 128 for CUB, 64 for Food101, 32 for OxfordPets, and 8 for EuroSAT. This could also be one of the reasons.

**Comment by StellarOdys2ey** [comment]
> Hi,
> 
> Thank you for bringing this up, there is indeed a bug in our code and some details are missing from the paper.
> 
> 1. We missed a temperature parameter in the sigmoid_metric() function. Now it has been updated and the metric scale should be correct. Thank you again for the debugging.
> 2. We use adaptive batch sizes for different datasets to alleviate the ambiguity within a batch. Specifically, we use a batch size that is smaller than the number of classes in the dataset. For example, we use 128 for CUB, 64 for Food101, 32 for OxfordPets, and 8 for EuroSAT. This could also be one of the reasons.

I really appreciate your answer. However, when I evaluated the Concept-level Explanation Disentanglability of zero-shot ViT-B/32 on all the datasets, the results ranged between 0.27 and 0.29. Even after adding the temperature parameter, I couldn't achieve the values reported in the paper (specifically, 0.361, 0.596, 0.487, 0.363, 0.192, with an average of 0.400). I believe this may not be related to the temperature parameter. Have you ever tested the Disentanglability of zero-shot ViT-B/32 using exp_disentanglability.ipynb?

**Comment by tangli-udel** [comment]
Thank you for your feedback.

Here are my reproduced results (all based on zero-shot CLIP-ViT-B-32, using a different machine):

Disentanglability: ImageNet (0.364), CUB (_0.554_), Food101 (_0.453_), OxfordPets (0.367), EuroSAT (0.199).
Localizability: ImageNet (0.630), CUB (_0.661_), Food101 (0.521), OxfordPets (_0.690_), EuroSAT (0.433).

Note that the results with italics show some fluctuations. Overall, I can largely reproduce the results from the paper on a different machine. Please try our latest code :)
